SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE `account`;
TRUNCATE TABLE `category`;
TRUNCATE TABLE `document`;
TRUNCATE TABLE `data_owner`;
TRUNCATE TABLE `data_owner_email`;
TRUNCATE TABLE `static_page`;
TRUNCATE TABLE `subscriber`;
TRUNCATE TABLE `updates`;

SET REFERENTIAL_INTEGRITY TRUE;
